import type { BetRecord, BetRepository, RoundRecord, RoundRepository } from "../application/repositories";
import type { SqlPool, SqlValue } from "./postgresContracts";
const text=(value:string):SqlValue=>({type:"text",value});
const nullableText=(value:string|null):SqlValue=>value===null?{type:"null",value:null}:text(value);
const numeric=(value:bigint):SqlValue=>({type:"numeric",value:value.toString()});
export class PostgreSqlRoundRepository implements RoundRepository {
 constructor(private readonly pool:SqlPool){}
 async get(roundId:string):Promise<RoundRecord|null>{const r=await this.pool.query<Record<string,unknown>>("SELECT round_id,provider_round_id,sequence,state,crash_multiplier,created_at,closed_at FROM aviator_rounds WHERE round_id = $1",[text(roundId)]);const x=r.rows[0];if(!x)return null;return {roundId:String(x.round_id),providerRoundId:x.provider_round_id==null?null:String(x.provider_round_id),sequence:Number(x.sequence),state:x.state as RoundRecord["state"],crashMultiplier:x.crash_multiplier==null?null:Number(x.crash_multiplier),createdAt:String(x.created_at),closedAt:x.closed_at==null?null:String(x.closed_at)};}
 async append(v:RoundRecord):Promise<void>{await this.pool.query("INSERT INTO aviator_rounds (round_id,provider_round_id,sequence,state,crash_multiplier,created_at,closed_at) VALUES ($1,$2,$3,$4,$5,$6,$7)",[text(v.roundId),nullableText(v.providerRoundId),{type:"int",value:v.sequence},text(v.state),v.crashMultiplier==null?{type:"null",value:null}:{type:"numeric",value:v.crashMultiplier},text(v.createdAt),nullableText(v.closedAt)]);}
 async updateState(roundId:string,state:RoundRecord["state"],closedAt?:string):Promise<void>{await this.pool.query("UPDATE aviator_rounds SET state=$2,closed_at=COALESCE($3,closed_at) WHERE round_id=$1",[text(roundId),text(state),closedAt===undefined?{type:"null",value:null}:text(closedAt)]);}
}
export class PostgreSqlBetRepository implements BetRepository {
 constructor(private readonly pool:SqlPool){}
 async get(betId:string):Promise<BetRecord|null>{const r=await this.pool.query<Record<string,unknown>>("SELECT bet_id,round_id,player_id,slot,stake_minor_units,state,auto_cash_out,cash_out_multiplier,payout_minor_units,created_at,settled_at FROM aviator_bets WHERE bet_id=$1",[text(betId)]);const x=r.rows[0];if(!x)return null;return {betId:String(x.bet_id),roundId:String(x.round_id),playerId:String(x.player_id),slot:x.slot as BetRecord["slot"],stakeMinorUnits:BigInt(String(x.stake_minor_units)),state:x.state as BetRecord["state"],autoCashOut:x.auto_cash_out==null?null:Number(x.auto_cash_out),cashOutMultiplier:x.cash_out_multiplier==null?null:Number(x.cash_out_multiplier),payoutMinorUnits:BigInt(String(x.payout_minor_units)),createdAt:String(x.created_at),settledAt:x.settled_at==null?null:String(x.settled_at)};}
 async append(v:BetRecord):Promise<void>{await this.pool.query("INSERT INTO aviator_bets (bet_id,round_id,player_id,slot,stake_minor_units,state,auto_cash_out,cash_out_multiplier,payout_minor_units,created_at,settled_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)",[text(v.betId),text(v.roundId),text(v.playerId),text(v.slot),numeric(v.stakeMinorUnits),text(v.state),v.autoCashOut==null?{type:"null",value:null}:{type:"numeric",value:v.autoCashOut},v.cashOutMultiplier==null?{type:"null",value:null}:{type:"numeric",value:v.cashOutMultiplier},numeric(v.payoutMinorUnits),text(v.createdAt),nullableText(v.settledAt)]);}
 async settle(id:string,state:BetRecord["state"],payout:bigint,mult:number|null,at:string):Promise<void>{await this.pool.query("UPDATE aviator_bets SET state=$2,payout_minor_units=$3,cash_out_multiplier=$4,settled_at=$5 WHERE bet_id=$1 AND settled_at IS NULL",[text(id),text(state),numeric(payout),mult==null?{type:"null",value:null}:{type:"numeric",value:mult},text(at)]);}
}
