import { useEffect, useState } from 'react';
import type { IGameProvider } from '../domain/IGameProvider';
import type { GameSnapshot, SlotId } from '../domain/game';
import type { EnvironmentId } from './Atmosphere';
import { Atmosphere } from './Atmosphere';
import { flightIntensityFromSnapshot } from './atmosphereController';
import './aviator.css';

type UIState = { stake:number; autoBet:boolean; autoCashOut:number|null; mode:'BET'|'AUTO' };
function roundLabel(state:string){ return state==='CRASH'?'CRASHED':state.replaceAll('_',' '); }

function icon(name:'menu'|'theme'|'aircraft'|'players'|'stats'|'learn'|'community'|'more'|'challenge'|'secure'|'fair'|'global'|'responsible'){
 const paths:Record<typeof name,string>={
  menu:'M4 7h16M4 12h16M4 17h16',theme:'M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6l1.4 1.4M17 17l1.4 1.4M18.4 5.6L17 7M7 17l-1.4 1.4M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z',
  aircraft:'M3 13h6l5-8 2 1-2 7h6l3 2-3 2h-6l2 7-2 1-5-8H3l-1-2 1-2Z',players:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',
  stats:'M4 19V9M10 19V5M16 19v-7M22 19V3',learn:'M3 5h7a2 2 0 0 1 2 2v12a2 2 0 0 0-2-2H3V5ZM21 5h-7a2 2 0 0 0-2 2v12a2 2 0 0 1 2-2h7V5Z',community:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75',more:'M5 12h.01M12 12h.01M19 12h.01',
  challenge:'M8 21h8M12 17v4M7 4h10v2a5 5 0 0 1-10 0V4ZM4 4h3v2a5 5 0 0 0 10 0V4h3M7 4V2h10v2',secure:'M12 3 5 6v5c0 4.4 2.9 8.4 7 10 4.1-1.6 7-5.6 7-10V6l-7-3Z',fair:'M12 3v18M5 7h14M7 7l-3 5a4 4 0 0 0 6 0L7 7ZM17 7l-3 5a4 4 0 0 0 6 0l-3-5Z',global:'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18ZM3 12h18M12 3c2.2 2.4 3.3 5.4 3.3 9s-1.1 6.6-3.3 9c-2.2-2.4-3.3-5.4-3.3-9S9.8 5.4 12 3Z',responsible:'M12 21s-8-4.4-8-10.2C4 7.4 6 5 8.8 5c1.5 0 2.6.7 3.2 1.8C12.6 5.7 13.7 5 15.2 5 18 5 20 7.4 20 10.8 20 16.6 12 21 12 21Z'
 };
 return <svg viewBox="0 0 24 24" className="ui-icon" aria-hidden="true"><path d={paths[name]}/></svg>;
}

function BetCard({id,slot,ui,round,setUI,place,cash}:{id:SlotId;slot:GameSnapshot['bets'][SlotId];ui:UIState;round:GameSnapshot['round'];setUI:(p:Partial<UIState>)=>void;place:()=>void;cash:()=>void}){
 const active=slot.state==='BET_PLACED'||slot.state==='ACTIVE',canPlace=round.state==='BETTING_OPEN'&&slot.state==='IDLE',canCash=round.state==='FLYING'&&active;
 const locked=active||slot.state==='CASHED_OUT'||slot.state==='CRASHED'||slot.state==='SETTLED';
 const action=canCash?'CASH OUT':ui.autoBet&&!canPlace?'BET (NEXT ROUND)':id==='BET1'?'BET 1':'BET 2';
 return <section className={'bet-card cockpit-bet '+(id==='BET1'?'bet-one':'bet-two')+(active?' is-live':'')}>
  <div className="cockpit-bet-head"><div className="cockpit-bet-title"><span className="bet-name">{id==='BET1'?'Bet 1':'Bet 2'}</span><span className="bet-state">{active?'LIVE':'IDLE'}</span></div><div className="potential-payout"><span>Potential Payout</span><strong>{'$'+payout.toFixed(2)+' ('+multiplier.toFixed(2)+'x)'}</strong></div></div>
  <div className="cockpit-controls">
   <div className="control-group"><label>Stake</label><div className="stake-stepper"><button type="button" disabled={locked} aria-label={id+' decrease stake'} onClick={()=>setUI({stake:Math.max(1,ui.stake-1)})}>−</button><input type="number" min="1" max="5000" value={ui.stake} disabled={locked} aria-label={id+' stake'} onChange={e=>setUI({stake:Math.max(1,Math.min(5000,Number(e.target.value)||1))})}/><button type="button" disabled={locked} aria-label={id+' increase stake'} onClick={()=>setUI({stake:Math.min(5000,ui.stake+1)})}>+</button></div><div className="quick-stakes cockpit-quick">{[1,5,10,50].map(v=><button key={v} type="button" disabled={locked} className={ui.stake===v?'selected':''} onClick={()=>setUI({stake:v})}>{v}</button>)}<button type="button" disabled={locked} className={ui.stake>=5000?'selected':''} onClick={()=>setUI({stake:5000})}>MAX</button></div></div>
   <div className="control-group auto-cashout-group"><div className="auto-cashout-head"><label htmlFor={id+'-auto-cashout'}>Auto Cashout</label></div><div className="stake-stepper"><button type="button" disabled={active||ui.autoCashOut===null} aria-label={id+' decrease auto cashout'} onClick={()=>setUI({autoCashOut:Math.max(1.05,Number(((ui.autoCashOut??2)-.1).toFixed(2)))})}>−</button><input type="number" step=".1" min="1.05" max="100" id={id+'-auto-cashout'} value={ui.autoCashOut??''} aria-label={id+' auto cashout multiplier'} disabled={active||ui.autoCashOut===null} onChange={e=>setUI({autoCashOut:Math.max(1.05,Math.min(100,Number(e.target.value)||2))})}/><button type="button" disabled={active||ui.autoCashOut===null} aria-label={id+' increase auto cashout'} onClick={()=>setUI({autoCashOut:Math.min(100,Number(((ui.autoCashOut??2)+.1).toFixed(2)))})}>+</button></div><button type="button" className={'auto-cashout-button '+(ui.autoCashOut!==null?'enabled':'')} disabled={active} aria-pressed={ui.autoCashOut!==null} onClick={()=>setUI({autoCashOut:ui.autoCashOut===null?2:null})}>Auto Cashout {ui.autoCashOut!==null?'ON':'OFF'}</button></div>
  </div>
  <div className="cockpit-action-row"><label className={'auto-bet-control '+(ui.autoBet?'enabled':'')}><span className="auto-badge">A</span><span className="auto-copy"><strong>Auto</strong><small>{ui.autoBet?'ON · NEXT ROUND':'OFF'}</small></span><input type="checkbox" checked={ui.autoBet} disabled={active} onChange={e=>setUI({autoBet:e.target.checked})}/><span className="switch-track"><span/></span></label><span className="action-divider" aria-hidden="true"/><button className="primary-bet-action cockpit-action" type="button" disabled={!canPlace&&!canCash} onClick={canCash?cash:place}><span className="action-plane">{icon('aircraft')}</span><span>{action}</span></button></div>
 </section>;
}

function DailyChallenge(){return <section className="daily-challenge"><div className="challenge-icon">{icon('challenge')}</div><div className="challenge-main"><strong>DAILY FLIGHT CHALLENGE</strong><p>Climb the leaderboard. Win rewards.</p><span>Stratosphere Ace (3/5 Complete)</span><div className="challenge-progress"><i/></div></div><span className="challenge-time">◷ Resets in 06h 42m</span><span className="chevron">→</span></section>}
function SessionStats({playerCount}:{playerCount:number}){return <section className="session-stats" aria-label="Session information"><div><strong>{playerCount}</strong><span>Players</span></div><div><strong>—</strong><span>Total Bets</span></div><div><strong>—</strong><span>Round Time</span></div></section>}

export function AviatorProductionApp({provider,environment='above-clouds'}:{provider:IGameProvider;environment?:EnvironmentId}){
 const [snapshot,setSnapshot]=useState(provider.snapshot()),[ui,setUI]=useState<Record<SlotId,UIState>>({BET1:{stake:10,autoBet:false,autoCashOut:2,mode:'BET'},BET2:{stake:25,autoBet:false,autoCashOut:3,mode:'BET'}}),[history,setHistory]=useState<number[]>([]);
 useEffect(()=>provider.subscribe(setSnapshot),[provider]);
 useEffect(()=>{if(snapshot.round.state==='RESULT'||snapshot.round.state==='CRASH'){const m=snapshot.round.multiplier;if(m>0)setHistory(c=>c[0]===m?c:[m,...c].slice(0,12))}},[snapshot.round.state,snapshot.round.multiplier]);
 const patch=(id:SlotId,v:Partial<UIState>)=>setUI(c=>({...c,[id]:{...c[id],...v}}));
 const place=(id:SlotId)=>provider.placeBet({slot:id,stake:ui[id].stake,autoBet:ui[id].autoBet,autoCashOut:ui[id].autoCashOut});
 const cash=(id:SlotId)=>{try{provider.cashOut(id)}catch{}};
 const progress=Math.min(1,Math.max(0,(snapshot.round.multiplier-1)/9)),aircraftX=10+progress*80,aircraftY=82-Math.pow(progress,1.55)*64,pathD='M 8 82 Q 24 80 38 68 T 60 46 T 76 28 T 90 14';
 return <div className="aviator-shell">
  <header className="aviator-header"><button className="menu-button header-menu" type="button" aria-label="Open menu">{icon('menu')}</button><div className="header-brand aviator-brand"><span className="brand-lockup"><b className="brand-mark">{icon('aircraft')}</b><strong>AVIATOR</strong></span><small>FLY BEYOND LIMITS</small></div><div className="header-actions"><button className="theme-button" type="button" aria-label="Toggle appearance">{icon('theme')}</button><div className="header-balance"><span>DEMO</span><strong>$1,000.00</strong></div><button className="deposit-button" type="button" aria-label="Open action menu">{icon('more')}</button></div></header>
  <aside className="desktop-rail left-rail"><div className="rail-title">● Live Round</div><div className="rail-subtitle">● Round #{snapshot.round.id}</div><div className="rail-status">{roundLabel(snapshot.round.state)}</div><div className="rail-history">{history.length?history.map((v,i)=><div key={i}><span className="history-pill">{v.toFixed(2)}x</span><small>recent</small></div>):<div className="rail-empty">Completed provider rounds will appear here.</div>}</div><button className="rail-link" type="button">Full History →</button></aside>
  <section className="panel flight"><div className="flight-status-row" aria-label="Live flight status"><span className="flight-live"><i/> LIVE</span><span className="flight-round">Round #{snapshot.round.id}</span><span className="flight-players">{icon('players')} {snapshot.round.playerCount.toLocaleString()}</span><span className="flight-quality">{icon('stats')} Good</span></div><div className="flight-scene"><Atmosphere environment={environment} intensity={flightIntensityFromSnapshot(snapshot)}/><div className="reference-stars"/><div className="reference-mountains"/><div className="reference-runway"/></div><div className="flight-axis" aria-hidden="true"><span>5.0x</span><span>4.0x</span><span>3.0x</span><span>2.0x</span><span>1.0x</span></div><svg className="flight-path" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><path className="flight-path-fill" d={pathD+' L 90 100 L 8 100 Z'}/><path className="flight-path-line" d={pathD}/></svg><div className="aircraft" style={{left:aircraftX+'%',top:aircraftY+'%'}} aria-hidden="true"><svg viewBox="0 0 96 48"><path d="M6 27 C18 26 31 24 43 20 L68 5 C72 3 76 4 73 9 L63 21 L87 24 C92 25 93 28 88 30 L61 32 L49 43 C46 46 42 45 44 40 L48 32 L25 34 L15 41 C12 43 9 41 11 37 L17 32 L7 31 C2 31 2 28 6 27Z" fill="currentColor"/></svg></div><div className="flight-copy"><div className="multiplier" aria-live="polite">{snapshot.round.multiplier.toFixed(2)}x</div><div className="flight-message">{snapshot.round.state==='FLYING'?'Keep it going...':roundLabel(snapshot.round.state)}</div></div></section>
  <aside className="desktop-rail right-rail"><div className="rail-title">{icon('players')} Live Players <strong>{snapshot.round.playerCount.toLocaleString()}</strong></div><div className="player-list"><div>Provider player feed <span>LIVE</span></div><div>Player identities <span>PRIVATE</span></div><div>Settlement feed <span>ACTIVE</span></div></div><div className="stats-box"><div>Players <strong>{snapshot.round.playerCount.toLocaleString()}</strong></div><div>Total Bets <strong>Provider</strong></div><div>Highest <strong>Provider</strong></div><div>Lowest <strong>Provider</strong></div></div></aside>
  <section className="bet-workspace">
   <div className="recent-multipliers mobile-first-recent"><div className="section-heading"><strong>Recent Multipliers</strong><button type="button">All Rounds →</button></div><div className="recent-row">{(history.length?history:[snapshot.round.multiplier]).slice(0,8).map((v,i)=><span key={i} className={'recent-chip '+(v>=2?'positive':'negative')}>{v.toFixed(2)}x</span>)}</div></div>
   <div className="bet-grid"><BetCard id="BET1" slot={snapshot.bets.BET1} ui={ui.BET1} round={snapshot.round} setUI={v=>patch('BET1',v)} place={()=>place('BET1')} cash={()=>cash('BET1')}/><BetCard id="BET2" slot={snapshot.bets.BET2} ui={ui.BET2} round={snapshot.round} setUI={v=>patch('BET2',v)} place={()=>place('BET2')} cash={()=>cash('BET2')}/></div>
   <DailyChallenge/><SessionStats playerCount={snapshot.round.playerCount}/>
   <div className="utility-grid"><button type="button"><span>{icon('learn')}</span><b>How to Play</b><small>Flight mechanics...</small></button><button type="button"><span>{icon('fair')}</span><b>Game Rules</b><small>Multiplier logic &amp; fairness</small></button><button type="button"><span>{icon('responsible')}</span><b>Game Limits</b><small>Min $1.00 · Max $5,000</small></button><button type="button"><span>{icon('secure')}</span><b>Probably Fair</b><small>Cryptographic verification</small></button></div>
   <footer className="aviator-footer"><strong>AVIATOR — ONE GAME. ONE FLIGHT. ONE PREMIUM EXPERIENCE.</strong><span>FLY BEYOND LIMITS • Standalone Simulation Interface &amp; Presentation Prototype</span></footer>
  </section>
  <nav className="mobile-nav" aria-label="Primary navigation"><button type="button" className="active"><span className="nav-icon">{icon('aircraft')}</span><span>Play</span></button><button type="button"><span className="nav-icon">{icon('stats')}</span><span>Stats</span></button><button type="button"><span className="nav-icon">{icon('learn')}</span><span>Learn</span></button><button type="button"><span className="nav-icon">{icon('community')}</span><span>Community</span></button><button type="button"><span className="nav-icon">{icon('more')}</span><span>More</span></button></nav>
  <footer className="trust-strip"><span>{icon('secure')} Secure <small>Provider-controlled funds</small></span><span>{icon('fair')} Fair <small>Auditable game state</small></span><span>{icon('global')} Global <small>Play anytime, anywhere</small></span><span>{icon('responsible')} Responsible <small>Play with control</small></span></footer>
 </div>;
}
